name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # 每次 push 到 main 分支触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        working-directory: doc-abbr-next
        run: npm install

      # 4️⃣ 构建 Next.js 静态站点
      - name: Build project
        working-directory: doc-abbr-next
        run: npm run build

      # 5️⃣ 添加 .nojekyll 避免 Jekyll 构建
      - name: Create .nojekyll
        run: echo "" > ./doc-abbr-next/out/.nojekyll

      # 6️⃣ 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}    # 使用你的 PAT
          publish_branch: gh-pages               # 部署目标分支
          publish_dir: ./doc-abbr-next/out       # 构建产物目录
          keep_files: true                       # 保留分支上其他文件
