name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main   # 每次 push 到 main 分支触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ 安装依赖
      - name: Install dependencies
        working-directory: doc-abbr-next
        run: npm install

      # 4️⃣ 构建 Next.js（静态导出）
      - name: Build project
        working-directory: doc-abbr-next
        run: npm run build

      # 5️⃣ 部署到 main 分支的 docs/ 子目录
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main           # 部署到 main 分支
          publish_dir: ./doc-abbr-next/out # 构建产物路径
          destination_dir: docs         # 只覆盖 docs/ 子目录
          keep_files: true              # 保留其他文件
